# Generated by Django 2.2 on 2021-08-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='drinks',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
