# Generated by Django 2.2 on 2021-08-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_drink',
        ),
    ]
