# Generated by Django 2.2 on 2021-08-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_order_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
