# Generated by Django 3.1.7 on 2021-08-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210816_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='main.order'),
        ),
    ]
